data_directory: "./data"  # Where to save extracted directories
ignore_files_regex: ["team[0-9]-model[a-zA-Z0-9].*", ".*licen[sc]e.*" ] # Regex to ignore certain files
repositories:
  - url: https://github.com/midas-network/rsv-scenario-modeling-hub
    branch: main
    directories:
      config: hub-config
      metadata: model-metadata
      abstract: model-abstract
      output: model-output

  # Example of additional repositories
  # - url: https://github.com/another-org/repo-name
  #   branch: develop
  #   directories:
  #     data: data
  #     models: models